LLM_KEY: "YOUR_LLM_KEY"
LLM_URL: "YOUR_LLM_URL"
LLM_MODEL_NAME: "YOUR_LLM_MODEL_NAME"
LLM_MAX_TOKENS:

REMOTE_EMBEDDING_ENDPOINT: "YOUR_EMBEDDING_MODEL_URL"
REMOTE_EMBEDDING_MODEL_NAME: "YOUR_MODEL_NAME"

servers:
  - ip: "127.0.0.1"
    host_user: "root"
    password: "password"
    port: 22
    app: "flink"
    target_process_name: "jobmanager"
    business_context: "高并发流处理服务，CPU负载主要集中在用户态算子与序列化反序列化"
    max_retries: 3
    delay: 1.0


#servers:
#  - ip: ""
#    host_user: ""
#    password: ""
#    port: 22
#    app: "mysql"
#    target_process_name: "mysqld"
#    max_retries: 3
#    delay: 1.0

#servers:
#  - ip: ""
#    host_user: ""
#    password: ""
#    port:
#    app: "spark"
#    target_process_name: "java"
#    business_context: "基于内存计算的分布式批处理框架，适合大规模数据处理任务，CPU负载主要集中在用户态的序列化、反序列化及任务调度执行过程"
#    max_retries: 3
#    delay: 1.0

# servers:
#  - ip: ""
#    host_user: ""
#    password: ""
#    port:
#     app: "gaussdb"
#     target_process_name: "gaussdb"
#     business_context: "高并发数据库服务，CPU负载主要集中在用户态处理"
#     max_retries: 3
#     delay: 1.0

#servers:
#  - ip: ""
#    host_user: ""
#    password: ""
#    port:
#    app: "nginx"
#    target_process_name: "nginx"
#    business_context: "高并发Web服务，CPU负载主要集中在用户态处理"
#    max_retries: 3
#    delay: 1.0

feature:
  - need_restart_application: False
    need_recover_cluster: False
    microDep_collector: True
    pressure_test_mode: True
    tune_system_param: False
    tune_app_param: True
    strategy_optimization: False
    benchmark_timeout: 3600

#是否开启大模型的ssl验证 enable 开启 disable 关闭 默认开启，当大模型无法通过ssl验证的时候可以改成disable
ssl: enable 
